import '../../resilience/models/gps_health.dart';
import '../../resilience/models/position_source.dart';
import '../../resilience/models/positioning_mode.dart';

/// Type of safety or emergency event.
enum SafetyEventType {
  sos,
  manualCheckIn,
  safetyAlert,
  locationUpdate,
  routeDeviation,
  systemHealth;

  String get label {
    switch (this) {
      case SafetyEventType.sos:
        return 'SOS';
      case SafetyEventType.manualCheckIn:
        return 'CHECK-IN';
      case SafetyEventType.safetyAlert:
        return 'ALERT';
      case SafetyEventType.locationUpdate:
        return 'LOCATION';
      case SafetyEventType.routeDeviation:
        return 'DEVIATION';
      case SafetyEventType.systemHealth:
        return 'HEALTH';
    }
  }
}

/// Delivery status of a safety event in the local store and communication pipeline.
enum EventDeliveryStatus {
  pending,
  queued,
  sending,
  sent,
  acknowledged,
  failed;

  String get label {
    switch (this) {
      case EventDeliveryStatus.pending:
        return 'PENDING';
      case EventDeliveryStatus.queued:
        return 'QUEUED';
      case EventDeliveryStatus.sending:
        return 'SENDING';
      case EventDeliveryStatus.sent:
        return 'SENT';
      case EventDeliveryStatus.acknowledged:
        return 'ACKNOWLEDGED';
      case EventDeliveryStatus.failed:
        return 'FAILED';
    }
  }

  bool get isFinal => this == EventDeliveryStatus.sent || this == EventDeliveryStatus.acknowledged;
  bool get isPendingOrQueued => this == EventDeliveryStatus.pending || this == EventDeliveryStatus.queued || this == EventDeliveryStatus.failed;
}

/// Persistent model representing a safety event generated by the user or system.
class SafetyEvent {
  /// Unique identifier (e.g. "SOS-1724356890123-A8F2").
  final String eventId;

  /// Type of safety event.
  final SafetyEventType eventType;

  /// Timestamp when the event was generated.
  final DateTime timestamp;

  /// Captured WGS-84 Latitude in degrees. Null if no position estimate was available.
  /// Strictly NEVER set to 0.0 for missing locations.
  final double? latitude;

  /// Captured WGS-84 Longitude in degrees. Null if no position estimate was available.
  /// Strictly NEVER set to 0.0 for missing locations.
  final double? longitude;

  /// Source of the captured position estimate at event creation time.
  final PositionSource? positionSource;

  /// Confidence score of the position estimate [0.0 to 1.0].
  final double? confidence;

  /// Horizontal position uncertainty in meters.
  final double? uncertaintyMeters;

  /// Positioning mode active when the event was generated.
  final PositioningMode? positioningMode;

  /// GPS health state at event creation.
  final GpsHealth? gpsHealth;

  /// True if internet was online when the event was generated.
  final bool internetAvailable;

  /// Current lifecycle delivery status.
  final EventDeliveryStatus eventStatus;

  /// Number of delivery transmission attempts made.
  final int retryCount;

  /// Local creation timestamp.
  final DateTime createdAt;

  /// Timestamp of the last delivery attempt.
  final DateTime? lastAttemptAt;

  /// Channel used for last successful/attempted delivery (e.g. "INTERNET", "OFFLINE_QUEUE", "SMS").
  final String? deliveryChannel;

  /// Failure reason if delivery encountered an error.
  final String? failureReason;

  /// Optional auxiliary metadata dictionary.
  final Map<String, dynamic>? metadata;

  const SafetyEvent({
    required this.eventId,
    required this.eventType,
    required this.timestamp,
    this.latitude,
    this.longitude,
    this.positionSource,
    this.confidence,
    this.uncertaintyMeters,
    this.positioningMode,
    this.gpsHealth,
    required this.internetAvailable,
    this.eventStatus = EventDeliveryStatus.pending,
    this.retryCount = 0,
    required this.createdAt,
    this.lastAttemptAt,
    this.deliveryChannel,
    this.failureReason,
    this.metadata,
  });

  /// True if the event contains valid non-zero geodetic coordinates.
  bool get hasValidLocation =>
      latitude != null &&
      longitude != null &&
      !(latitude == 0.0 && longitude == 0.0);

  SafetyEvent copyWith({
    String? eventId,
    SafetyEventType? eventType,
    DateTime? timestamp,
    double? latitude,
    double? longitude,
    PositionSource? positionSource,
    double? confidence,
    double? uncertaintyMeters,
    PositioningMode? positioningMode,
    GpsHealth? gpsHealth,
    bool? internetAvailable,
    EventDeliveryStatus? eventStatus,
    int? retryCount,
    DateTime? createdAt,
    DateTime? lastAttemptAt,
    String? deliveryChannel,
    String? failureReason,
    Map<String, dynamic>? metadata,
  }) {
    return SafetyEvent(
      eventId: eventId ?? this.eventId,
      eventType: eventType ?? this.eventType,
      timestamp: timestamp ?? this.timestamp,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      positionSource: positionSource ?? this.positionSource,
      confidence: confidence ?? this.confidence,
      uncertaintyMeters: uncertaintyMeters ?? this.uncertaintyMeters,
      positioningMode: positioningMode ?? this.positioningMode,
      gpsHealth: gpsHealth ?? this.gpsHealth,
      internetAvailable: internetAvailable ?? this.internetAvailable,
      eventStatus: eventStatus ?? this.eventStatus,
      retryCount: retryCount ?? this.retryCount,
      createdAt: createdAt ?? this.createdAt,
      lastAttemptAt: lastAttemptAt ?? this.lastAttemptAt,
      deliveryChannel: deliveryChannel ?? this.deliveryChannel,
      failureReason: failureReason ?? this.failureReason,
      metadata: metadata ?? this.metadata,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'eventId': eventId,
      'eventType': eventType.name,
      'timestamp': timestamp.toIso8601String(),
      'latitude': latitude,
      'longitude': longitude,
      'positionSource': positionSource?.name,
      'confidence': confidence,
      'uncertaintyMeters': uncertaintyMeters,
      'positioningMode': positioningMode?.name,
      'gpsHealth': gpsHealth?.name,
      'internetAvailable': internetAvailable,
      'eventStatus': eventStatus.name,
      'retryCount': retryCount,
      'createdAt': createdAt.toIso8601String(),
      'lastAttemptAt': lastAttemptAt?.toIso8601String(),
      'deliveryChannel': deliveryChannel,
      'failureReason': failureReason,
      'metadata': metadata,
    };
  }

  factory SafetyEvent.fromJson(Map<String, dynamic> json) {
    return SafetyEvent(
      eventId: json['eventId'] as String,
      eventType: SafetyEventType.values.firstWhere(
        (e) => e.name == json['eventType'],
        orElse: () => SafetyEventType.sos,
      ),
      timestamp: DateTime.parse(json['timestamp'] as String),
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      positionSource: json['positionSource'] != null
          ? PositionSource.values.firstWhere(
              (e) => e.name == json['positionSource'],
              orElse: () => PositionSource.lastKnown,
            )
          : null,
      confidence: (json['confidence'] as num?)?.toDouble(),
      uncertaintyMeters: (json['uncertaintyMeters'] as num?)?.toDouble(),
      positioningMode: json['positioningMode'] != null
          ? PositioningMode.values.firstWhere(
              (e) => e.name == json['positioningMode'],
              orElse: () => PositioningMode.pdrFallback,
            )
          : null,
      gpsHealth: json['gpsHealth'] != null
          ? GpsHealth.values.firstWhere(
              (e) => e.name == json['gpsHealth'],
              orElse: () => GpsHealth.disabled,
            )
          : null,
      internetAvailable: (json['internetAvailable'] as bool?) ?? false,
      eventStatus: EventDeliveryStatus.values.firstWhere(
        (e) => e.name == json['eventStatus'],
        orElse: () => EventDeliveryStatus.pending,
      ),
      retryCount: (json['retryCount'] as int?) ?? 0,
      createdAt: DateTime.parse(json['createdAt'] as String),
      lastAttemptAt: json['lastAttemptAt'] != null
          ? DateTime.parse(json['lastAttemptAt'] as String)
          : null,
      deliveryChannel: json['deliveryChannel'] as String?,
      failureReason: json['failureReason'] as String?,
      metadata: json['metadata'] != null
          ? Map<String, dynamic>.from(json['metadata'] as Map)
          : null,
    );
  }

  @override
  String toString() {
    return 'SafetyEvent($eventId, type=$eventType, status=$eventStatus, '
        'pos=(${latitude?.toStringAsFixed(5) ?? "null"}, ${longitude?.toStringAsFixed(5) ?? "null"}), '
        'source=$positionSource, net=$internetAvailable, retries=$retryCount)';
  }
}
